# Generated by Django 3.1 on 2023-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
