# Generated by Django 3.1 on 2023-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230515_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
