# Generated by Django 3.1 on 2023-05-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='address',
        ),
    ]
