# Generated by Django 3.1 on 2023-05-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
